#生产环境配置文件

server:
  port: 80

spring:
  elasticsearch:
    rest:
      uris: 101.42.36.102:9200
      username: elastic
      password: ENC(7E0aanxYXFQZE7p1n0J9ZapkjycnIE2Y)
  datasource:
    druid:
      url: jdbc:mysql://101.42.36.102:3306/lq?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      password: ENC(4uvIx9GEADNUTe8IUlEmG87P74fVrPWZ)
  thymeleaf:
    cache: true

logging:
  level:
    cn.lq: warn

swagger:
  show: false